//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

using System.ComponentModel.DataAnnotations;

[assembly: EdmSchemaAttribute()]
namespace MesaPartes.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BIBLIO_UCSMEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BIBLIO_UCSMEntities usando la cadena de conexión encontrada en la sección 'BIBLIO_UCSMEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BIBLIO_UCSMEntities() : base("name=BIBLIO_UCSMEntities", "BIBLIO_UCSMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BIBLIO_UCSMEntities.
        /// </summary>
        public BIBLIO_UCSMEntities(string connectionString) : base(connectionString, "BIBLIO_UCSMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BIBLIO_UCSMEntities.
        /// </summary>
        public BIBLIO_UCSMEntities(EntityConnection connection) : base(connection, "BIBLIO_UCSMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<AuditoriaConstancias> AuditoriaConstancias
        {
            get
            {
                if ((_AuditoriaConstancias == null))
                {
                    _AuditoriaConstancias = base.CreateObjectSet<AuditoriaConstancias>("AuditoriaConstancias");
                }
                return _AuditoriaConstancias;
            }
        }
        private ObjectSet<AuditoriaConstancias> _AuditoriaConstancias;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Expedientes> Expedientes
        {
            get
            {
                if ((_Expedientes == null))
                {
                    _Expedientes = base.CreateObjectSet<Expedientes>("Expedientes");
                }
                return _Expedientes;
            }
        }
        private ObjectSet<Expedientes> _Expedientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<MaestroBiblio> MaestroBiblio
        {
            get
            {
                if ((_MaestroBiblio == null))
                {
                    _MaestroBiblio = base.CreateObjectSet<MaestroBiblio>("MaestroBiblio");
                }
                return _MaestroBiblio;
            }
        }
        private ObjectSet<MaestroBiblio> _MaestroBiblio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet AuditoriaConstancias. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAuditoriaConstancias(AuditoriaConstancias auditoriaConstancias)
        {
            base.AddObject("AuditoriaConstancias", auditoriaConstancias);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Expedientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToExpedientes(Expedientes expedientes)
        {
            base.AddObject("Expedientes", expedientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet MaestroBiblio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMaestroBiblio(MaestroBiblio maestroBiblio)
        {
            base.AddObject("MaestroBiblio", maestroBiblio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BIBLIO_UCSMModel", Name="AuditoriaConstancias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditoriaConstancias : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto AuditoriaConstancias.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="cIdExpediente">Valor inicial de la propiedad cIdExpediente.</param>
        /// <param name="cCodLector">Valor inicial de la propiedad cCodLector.</param>
        /// <param name="cCodPapelConstanc">Valor inicial de la propiedad cCodPapelConstanc.</param>
        /// <param name="reciboPapel">Valor inicial de la propiedad ReciboPapel.</param>
        /// <param name="reciboSistema">Valor inicial de la propiedad ReciboSistema.</param>
        /// <param name="hora_Expediente">Valor inicial de la propiedad Hora_Expediente.</param>
        /// <param name="fec_Expedición">Valor inicial de la propiedad Fec_Expedición.</param>
        /// <param name="control">Valor inicial de la propiedad Control.</param>
        /// <param name="anular">Valor inicial de la propiedad Anular.</param>
        /// <param name="cusuario">Valor inicial de la propiedad cusuario.</param>
        public static AuditoriaConstancias CreateAuditoriaConstancias(global::System.Decimal id, global::System.String cIdExpediente, global::System.String cCodLector, global::System.String cCodPapelConstanc, global::System.String reciboPapel, global::System.String reciboSistema, global::System.TimeSpan hora_Expediente, global::System.DateTime fec_Expedición, global::System.String control, global::System.String anular, global::System.String cusuario)
        {
            AuditoriaConstancias auditoriaConstancias = new AuditoriaConstancias();
            auditoriaConstancias.Id = id;
            auditoriaConstancias.cIdExpediente = cIdExpediente;
            auditoriaConstancias.cCodLector = cCodLector;
            auditoriaConstancias.cCodPapelConstanc = cCodPapelConstanc;
            auditoriaConstancias.ReciboPapel = reciboPapel;
            auditoriaConstancias.ReciboSistema = reciboSistema;
            auditoriaConstancias.Hora_Expediente = hora_Expediente;
            auditoriaConstancias.Fec_Expedición = fec_Expedición;
            auditoriaConstancias.Control = control;
            auditoriaConstancias.Anular = anular;
            auditoriaConstancias.cusuario = cusuario;
            return auditoriaConstancias;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [DisplayName("Nro Expediente")]
        [Required(ErrorMessage = "Escriba el numero del expediente")]
        [RegularExpression("([0-9]{10})", ErrorMessage = "Debe contener solo numeros ( 10 digitos )")]
        public global::System.String cIdExpediente
        {
            get
            {
                return _cIdExpediente;
            }
            set
            {
                if (_cIdExpediente != value)
                {
                    OncIdExpedienteChanging(value);
                    ReportPropertyChanging("cIdExpediente");
                    _cIdExpediente = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cIdExpediente");
                    OncIdExpedienteChanged();
                }
            }
        }
        private global::System.String _cIdExpediente;
        partial void OncIdExpedienteChanging(global::System.String value);
        partial void OncIdExpedienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [DisplayName("Codigo del alumno")]
        [Required(ErrorMessage = "Escriba el codigo del alumno")]
        [StringLength(10, ErrorMessage = "Maximo de 10 digitos")]
        [RegularExpression("([0-9]+)", ErrorMessage = "escriba solo numeros")]
        public global::System.String cCodLector
        {
            get
            {
                return _cCodLector;
            }
            set
            {
                OncCodLectorChanging(value);
                ReportPropertyChanging("cCodLector");
                _cCodLector = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cCodLector");
                OncCodLectorChanged();
            }
        }
        private global::System.String _cCodLector;
        partial void OncCodLectorChanging(global::System.String value);
        partial void OncCodLectorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [DisplayName("Numero de Papel de constancia")]
        [Required(ErrorMessage = "Escriba el numero del papel de la constancia")]
        [StringLength(10, ErrorMessage = "Maximo de 10 digitos")]
        [RegularExpression("([0-9]){8}", ErrorMessage = "Escriba solo numeros de 8 digitos")]
        public global::System.String cCodPapelConstanc
        {
            get
            {
                return _cCodPapelConstanc;
            }
            set
            {
                OncCodPapelConstancChanging(value);
                ReportPropertyChanging("cCodPapelConstanc");
                _cCodPapelConstanc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cCodPapelConstanc");
                OncCodPapelConstancChanged();
            }
        }
        private global::System.String _cCodPapelConstanc;
        partial void OncCodPapelConstancChanging(global::System.String value);
        partial void OncCodPapelConstancChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [DisplayName("Numero Recibo")]
        [Required(ErrorMessage = "Escriba el numero del recibo")]
        [RegularExpression("([0-9]){10}", ErrorMessage = "Escriba solo numeros de 10 digitos")]
        public global::System.String ReciboPapel
        {
            get
            {
                return _ReciboPapel;
            }
            set
            {
                OnReciboPapelChanging(value);
                ReportPropertyChanging("ReciboPapel");
                _ReciboPapel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReciboPapel");
                OnReciboPapelChanged();
            }
        }
        private global::System.String _ReciboPapel;
        partial void OnReciboPapelChanging(global::System.String value);
        partial void OnReciboPapelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [DisplayName("Numero de Recibo del Sistema")]
        [Required(ErrorMessage = "Escriba el numero de Recibo del Sistema")]
        [RegularExpression("([0-9]){15}", ErrorMessage = "Escriba solo numeros de 15 digitos")]
        public global::System.String ReciboSistema
        {
            get
            {
                return _ReciboSistema;
            }
            set
            {
                OnReciboSistemaChanging(value);
                ReportPropertyChanging("ReciboSistema");
                _ReciboSistema = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReciboSistema");
                OnReciboSistemaChanged();
            }
        }
        private global::System.String _ReciboSistema;
        partial void OnReciboSistemaChanging(global::System.String value);
        partial void OnReciboSistemaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Hora_Expediente
        {
            get
            {
                return _Hora_Expediente;
            }
            set
            {
                OnHora_ExpedienteChanging(value);
                ReportPropertyChanging("Hora_Expediente");
                _Hora_Expediente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hora_Expediente");
                OnHora_ExpedienteChanged();
            }
        }
        private global::System.TimeSpan _Hora_Expediente;
        partial void OnHora_ExpedienteChanging(global::System.TimeSpan value);
        partial void OnHora_ExpedienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fec_Expedición
        {
            get
            {
                return _Fec_Expedición;
            }
            set
            {
                OnFec_ExpediciónChanging(value);
                ReportPropertyChanging("Fec_Expedición");
                _Fec_Expedición = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fec_Expedición");
                OnFec_ExpediciónChanged();
            }
        }
        private global::System.DateTime _Fec_Expedición;
        partial void OnFec_ExpediciónChanging(global::System.DateTime value);
        partial void OnFec_ExpediciónChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Control
        {
            get
            {
                return _Control;
            }
            set
            {
                OnControlChanging(value);
                ReportPropertyChanging("Control");
                _Control = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Control");
                OnControlChanged();
            }
        }
        private global::System.String _Control;
        partial void OnControlChanging(global::System.String value);
        partial void OnControlChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Anular
        {
            get
            {
                return _Anular;
            }
            set
            {
                OnAnularChanging(value);
                ReportPropertyChanging("Anular");
                _Anular = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Anular");
                OnAnularChanged();
            }
        }
        private global::System.String _Anular;
        partial void OnAnularChanging(global::System.String value);
        partial void OnAnularChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacion
        {
            get
            {
                return _Observacion;
            }
            set
            {
                OnObservacionChanging(value);
                ReportPropertyChanging("Observacion");
                _Observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacion");
                OnObservacionChanged();
            }
        }
        private global::System.String _Observacion;
        partial void OnObservacionChanging(global::System.String value);
        partial void OnObservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cusuario
        {
            get
            {
                return _cusuario;
            }
            set
            {
                OncusuarioChanging(value);
                ReportPropertyChanging("cusuario");
                _cusuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cusuario");
                OncusuarioChanged();
            }
        }
        private global::System.String _cusuario;
        partial void OncusuarioChanging(global::System.String value);
        partial void OncusuarioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BIBLIO_UCSMModel", Name="Expedientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Expedientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Expedientes.
        /// </summary>
        /// <param name="cIdExpediente">Valor inicial de la propiedad cIdExpediente.</param>
        /// <param name="cSalida">Valor inicial de la propiedad cSalida.</param>
        /// <param name="fec_Expedición">Valor inicial de la propiedad Fec_Expedición.</param>
        public static Expedientes CreateExpedientes(global::System.String cIdExpediente, global::System.Int32 cSalida, global::System.DateTime fec_Expedición)
        {
            Expedientes expedientes = new Expedientes();
            expedientes.cIdExpediente = cIdExpediente;
            expedientes.cSalida = cSalida;
            expedientes.Fec_Expedición = fec_Expedición;
            return expedientes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cIdExpediente
        {
            get
            {
                return _cIdExpediente;
            }
            set
            {
                if (_cIdExpediente != value)
                {
                    OncIdExpedienteChanging(value);
                    ReportPropertyChanging("cIdExpediente");
                    _cIdExpediente = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cIdExpediente");
                    OncIdExpedienteChanged();
                }
            }
        }
        private global::System.String _cIdExpediente;
        partial void OncIdExpedienteChanging(global::System.String value);
        partial void OncIdExpedienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cCodLector
        {
            get
            {
                return _cCodLector;
            }
            set
            {
                OncCodLectorChanging(value);
                ReportPropertyChanging("cCodLector");
                _cCodLector = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cCodLector");
                OncCodLectorChanged();
            }
        }
        private global::System.String _cCodLector;
        partial void OncCodLectorChanging(global::System.String value);
        partial void OncCodLectorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cSalida
        {
            get
            {
                return _cSalida;
            }
            set
            {
                OncSalidaChanging(value);
                ReportPropertyChanging("cSalida");
                _cSalida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cSalida");
                OncSalidaChanged();
            }
        }
        private global::System.Int32 _cSalida;
        partial void OncSalidaChanging(global::System.Int32 value);
        partial void OncSalidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fec_Expedición
        {
            get
            {
                return _Fec_Expedición;
            }
            set
            {
                OnFec_ExpediciónChanging(value);
                ReportPropertyChanging("Fec_Expedición");
                _Fec_Expedición = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fec_Expedición");
                OnFec_ExpediciónChanged();
            }
        }
        private global::System.DateTime _Fec_Expedición;
        partial void OnFec_ExpediciónChanging(global::System.DateTime value);
        partial void OnFec_ExpediciónChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CIdPrograma
        {
            get
            {
                return _CIdPrograma;
            }
            set
            {
                OnCIdProgramaChanging(value);
                ReportPropertyChanging("CIdPrograma");
                _CIdPrograma = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CIdPrograma");
                OnCIdProgramaChanged();
            }
        }
        private global::System.String _CIdPrograma;
        partial void OnCIdProgramaChanging(global::System.String value);
        partial void OnCIdProgramaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cDatos
        {
            get
            {
                return _cDatos;
            }
            set
            {
                OncDatosChanging(value);
                ReportPropertyChanging("cDatos");
                _cDatos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cDatos");
                OncDatosChanged();
            }
        }
        private global::System.String _cDatos;
        partial void OncDatosChanging(global::System.String value);
        partial void OncDatosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cusuario
        {
            get
            {
                return _cusuario;
            }
            set
            {
                OncusuarioChanging(value);
                ReportPropertyChanging("cusuario");
                _cusuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cusuario");
                OncusuarioChanged();
            }
        }
        private global::System.String _cusuario;
        partial void OncusuarioChanging(global::System.String value);
        partial void OncusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String anular
        {
            get
            {
                return _anular;
            }
            set
            {
                OnanularChanging(value);
                ReportPropertyChanging("anular");
                _anular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("anular");
                OnanularChanged();
            }
        }
        private global::System.String _anular;
        partial void OnanularChanging(global::System.String value);
        partial void OnanularChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BIBLIO_UCSMModel", Name="MaestroBiblio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MaestroBiblio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto MaestroBiblio.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="cod_barras">Valor inicial de la propiedad Cod_barras.</param>
        /// <param name="estado">Valor inicial de la propiedad Estado.</param>
        public static MaestroBiblio CreateMaestroBiblio(global::System.Decimal id, global::System.String cod_barras, global::System.String estado)
        {
            MaestroBiblio maestroBiblio = new MaestroBiblio();
            maestroBiblio.Id = id;
            maestroBiblio.Cod_barras = cod_barras;
            maestroBiblio.Estado = estado;
            return maestroBiblio;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cod_barras
        {
            get
            {
                return _Cod_barras;
            }
            set
            {
                if (_Cod_barras != value)
                {
                    OnCod_barrasChanging(value);
                    ReportPropertyChanging("Cod_barras");
                    _Cod_barras = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Cod_barras");
                    OnCod_barrasChanged();
                }
            }
        }
        private global::System.String _Cod_barras;
        partial void OnCod_barrasChanging(global::System.String value);
        partial void OnCod_barrasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [Required(ErrorMessage = "Escriba el codigo del alumno.")]
        [StringLength(10, ErrorMessage = "Maximo de 10 digitos")]
        [RegularExpression("([0-9]+)", ErrorMessage = "escriba solo numeros")]
        [Display(Name = "Codigo del Alumno")]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dni
        {
            get
            {
                return _dni;
            }
            set
            {
                OndniChanging(value);
                ReportPropertyChanging("dni");
                _dni = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dni");
                OndniChanged();
            }
        }
        private global::System.String _dni;
        partial void OndniChanging(global::System.String value);
        partial void OndniChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String datos
        {
            get
            {
                return _datos;
            }
            set
            {
                OndatosChanging(value);
                ReportPropertyChanging("datos");
                _datos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("datos");
                OndatosChanged();
            }
        }
        private global::System.String _datos;
        partial void OndatosChanging(global::System.String value);
        partial void OndatosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Categoria
        {
            get
            {
                return _Categoria;
            }
            set
            {
                OnCategoriaChanging(value);
                ReportPropertyChanging("Categoria");
                _Categoria = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Categoria");
                OnCategoriaChanged();
            }
        }
        private global::System.String _Categoria;
        partial void OnCategoriaChanging(global::System.String value);
        partial void OnCategoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cod_prog
        {
            get
            {
                return _cod_prog;
            }
            set
            {
                Oncod_progChanging(value);
                ReportPropertyChanging("cod_prog");
                _cod_prog = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cod_prog");
                Oncod_progChanged();
            }
        }
        private global::System.String _cod_prog;
        partial void Oncod_progChanging(global::System.String value);
        partial void Oncod_progChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String programa
        {
            get
            {
                return _programa;
            }
            set
            {
                OnprogramaChanging(value);
                ReportPropertyChanging("programa");
                _programa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("programa");
                OnprogramaChanged();
            }
        }
        private global::System.String _programa;
        partial void OnprogramaChanging(global::System.String value);
        partial void OnprogramaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha_venc
        {
            get
            {
                return _Fecha_venc;
            }
            set
            {
                OnFecha_vencChanging(value);
                ReportPropertyChanging("Fecha_venc");
                _Fecha_venc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_venc");
                OnFecha_vencChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha_venc;
        partial void OnFecha_vencChanging(Nullable<global::System.DateTime> value);
        partial void OnFecha_vencChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo1
        {
            get
            {
                return _campo1;
            }
            set
            {
                Oncampo1Changing(value);
                ReportPropertyChanging("campo1");
                _campo1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo1");
                Oncampo1Changed();
            }
        }
        private global::System.String _campo1;
        partial void Oncampo1Changing(global::System.String value);
        partial void Oncampo1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo2
        {
            get
            {
                return _campo2;
            }
            set
            {
                Oncampo2Changing(value);
                ReportPropertyChanging("campo2");
                _campo2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo2");
                Oncampo2Changed();
            }
        }
        private global::System.String _campo2;
        partial void Oncampo2Changing(global::System.String value);
        partial void Oncampo2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo3
        {
            get
            {
                return _campo3;
            }
            set
            {
                Oncampo3Changing(value);
                ReportPropertyChanging("campo3");
                _campo3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo3");
                Oncampo3Changed();
            }
        }
        private global::System.String _campo3;
        partial void Oncampo3Changing(global::System.String value);
        partial void Oncampo3Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo4
        {
            get
            {
                return _campo4;
            }
            set
            {
                Oncampo4Changing(value);
                ReportPropertyChanging("campo4");
                _campo4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo4");
                Oncampo4Changed();
            }
        }
        private global::System.String _campo4;
        partial void Oncampo4Changing(global::System.String value);
        partial void Oncampo4Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo5
        {
            get
            {
                return _campo5;
            }
            set
            {
                Oncampo5Changing(value);
                ReportPropertyChanging("campo5");
                _campo5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo5");
                Oncampo5Changed();
            }
        }
        private global::System.String _campo5;
        partial void Oncampo5Changing(global::System.String value);
        partial void Oncampo5Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo6
        {
            get
            {
                return _campo6;
            }
            set
            {
                Oncampo6Changing(value);
                ReportPropertyChanging("campo6");
                _campo6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo6");
                Oncampo6Changed();
            }
        }
        private global::System.String _campo6;
        partial void Oncampo6Changing(global::System.String value);
        partial void Oncampo6Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo7
        {
            get
            {
                return _campo7;
            }
            set
            {
                Oncampo7Changing(value);
                ReportPropertyChanging("campo7");
                _campo7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo7");
                Oncampo7Changed();
            }
        }
        private global::System.String _campo7;
        partial void Oncampo7Changing(global::System.String value);
        partial void Oncampo7Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo8
        {
            get
            {
                return _campo8;
            }
            set
            {
                Oncampo8Changing(value);
                ReportPropertyChanging("campo8");
                _campo8 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo8");
                Oncampo8Changed();
            }
        }
        private global::System.String _campo8;
        partial void Oncampo8Changing(global::System.String value);
        partial void Oncampo8Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo9
        {
            get
            {
                return _campo9;
            }
            set
            {
                Oncampo9Changing(value);
                ReportPropertyChanging("campo9");
                _campo9 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo9");
                Oncampo9Changed();
            }
        }
        private global::System.String _campo9;
        partial void Oncampo9Changing(global::System.String value);
        partial void Oncampo9Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo10
        {
            get
            {
                return _campo10;
            }
            set
            {
                Oncampo10Changing(value);
                ReportPropertyChanging("campo10");
                _campo10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo10");
                Oncampo10Changed();
            }
        }
        private global::System.String _campo10;
        partial void Oncampo10Changing(global::System.String value);
        partial void Oncampo10Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo11
        {
            get
            {
                return _campo11;
            }
            set
            {
                Oncampo11Changing(value);
                ReportPropertyChanging("campo11");
                _campo11 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo11");
                Oncampo11Changed();
            }
        }
        private global::System.String _campo11;
        partial void Oncampo11Changing(global::System.String value);
        partial void Oncampo11Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo12
        {
            get
            {
                return _campo12;
            }
            set
            {
                Oncampo12Changing(value);
                ReportPropertyChanging("campo12");
                _campo12 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo12");
                Oncampo12Changed();
            }
        }
        private global::System.String _campo12;
        partial void Oncampo12Changing(global::System.String value);
        partial void Oncampo12Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo13
        {
            get
            {
                return _campo13;
            }
            set
            {
                Oncampo13Changing(value);
                ReportPropertyChanging("campo13");
                _campo13 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo13");
                Oncampo13Changed();
            }
        }
        private global::System.String _campo13;
        partial void Oncampo13Changing(global::System.String value);
        partial void Oncampo13Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campo14
        {
            get
            {
                return _campo14;
            }
            set
            {
                Oncampo14Changing(value);
                ReportPropertyChanging("campo14");
                _campo14 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campo14");
                Oncampo14Changed();
            }
        }
        private global::System.String _campo14;
        partial void Oncampo14Changing(global::System.String value);
        partial void Oncampo14Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel_fij
        {
            get
            {
                return _tel_fij;
            }
            set
            {
                Ontel_fijChanging(value);
                ReportPropertyChanging("tel_fij");
                _tel_fij = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tel_fij");
                Ontel_fijChanged();
            }
        }
        private global::System.String _tel_fij;
        partial void Ontel_fijChanging(global::System.String value);
        partial void Ontel_fijChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String activo
        {
            get
            {
                return _activo;
            }
            set
            {
                OnactivoChanging(value);
                ReportPropertyChanging("activo");
                _activo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("activo");
                OnactivoChanged();
            }
        }
        private global::System.String _activo;
        partial void OnactivoChanging(global::System.String value);
        partial void OnactivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cybertesis
        {
            get
            {
                return _cybertesis;
            }
            set
            {
                OncybertesisChanging(value);
                ReportPropertyChanging("cybertesis");
                _cybertesis = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cybertesis");
                OncybertesisChanged();
            }
        }
        private global::System.String _cybertesis;
        partial void OncybertesisChanging(global::System.String value);
        partial void OncybertesisChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_registro
        {
            get
            {
                return _fecha_registro;
            }
            set
            {
                Onfecha_registroChanging(value);
                ReportPropertyChanging("fecha_registro");
                _fecha_registro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_registro");
                Onfecha_registroChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_registro;
        partial void Onfecha_registroChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_registroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo_lector
        {
            get
            {
                return _Tipo_lector;
            }
            set
            {
                OnTipo_lectorChanging(value);
                ReportPropertyChanging("Tipo_lector");
                _Tipo_lector = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo_lector");
                OnTipo_lectorChanged();
            }
        }
        private global::System.String _Tipo_lector;
        partial void OnTipo_lectorChanging(global::System.String value);
        partial void OnTipo_lectorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String biblioteca
        {
            get
            {
                return _biblioteca;
            }
            set
            {
                OnbibliotecaChanging(value);
                ReportPropertyChanging("biblioteca");
                _biblioteca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("biblioteca");
                OnbibliotecaChanged();
            }
        }
        private global::System.String _biblioteca;
        partial void OnbibliotecaChanging(global::System.String value);
        partial void OnbibliotecaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Acceso_Aleph
        {
            get
            {
                return _Acceso_Aleph;
            }
            set
            {
                OnAcceso_AlephChanging(value);
                ReportPropertyChanging("Acceso_Aleph");
                _Acceso_Aleph = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Acceso_Aleph");
                OnAcceso_AlephChanged();
            }
        }
        private global::System.String _Acceso_Aleph;
        partial void OnAcceso_AlephChanging(global::System.String value);
        partial void OnAcceso_AlephChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BIBLIO_UCSMModel", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuarios.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="cUsuario">Valor inicial de la propiedad cUsuario.</param>
        /// <param name="idTipPerBiblio">Valor inicial de la propiedad IdTipPerBiblio.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 id, global::System.String cUsuario, global::System.String idTipPerBiblio)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.Id = id;
            usuarios.cUsuario = cUsuario;
            usuarios.IdTipPerBiblio = idTipPerBiblio;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [DisplayName("Usuario")]
        [Required(ErrorMessage = "Escriba su usuario")]
        public global::System.String cUsuario
        {
            get
            {
                return _cUsuario;
            }
            set
            {
                if (_cUsuario != value)
                {
                    OncUsuarioChanging(value);
                    ReportPropertyChanging("cUsuario");
                    _cUsuario = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cUsuario");
                    OncUsuarioChanged();
                }
            }
        }
        private global::System.String _cUsuario;
        partial void OncUsuarioChanging(global::System.String value);
        partial void OncUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [DisplayName("Password")]
        [Required(ErrorMessage = "Escriba su password")]
        public global::System.String cContraseña
        {
            get
            {
                return _cContraseña;
            }
            set
            {
                OncContraseñaChanging(value);
                ReportPropertyChanging("cContraseña");
                _cContraseña = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cContraseña");
                OncContraseñaChanged();
            }
        }
        private global::System.String _cContraseña;
        partial void OncContraseñaChanging(global::System.String value);
        partial void OncContraseñaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cCod_usuario
        {
            get
            {
                return _cCod_usuario;
            }
            set
            {
                OncCod_usuarioChanging(value);
                ReportPropertyChanging("cCod_usuario");
                _cCod_usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cCod_usuario");
                OncCod_usuarioChanged();
            }
        }
        private global::System.String _cCod_usuario;
        partial void OncCod_usuarioChanging(global::System.String value);
        partial void OncCod_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cdatos
        {
            get
            {
                return _cdatos;
            }
            set
            {
                OncdatosChanging(value);
                ReportPropertyChanging("cdatos");
                _cdatos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cdatos");
                OncdatosChanged();
            }
        }
        private global::System.String _cdatos;
        partial void OncdatosChanging(global::System.String value);
        partial void OncdatosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cIdArea
        {
            get
            {
                return _cIdArea;
            }
            set
            {
                OncIdAreaChanging(value);
                ReportPropertyChanging("cIdArea");
                _cIdArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cIdArea");
                OncIdAreaChanged();
            }
        }
        private Nullable<global::System.Int32> _cIdArea;
        partial void OncIdAreaChanging(Nullable<global::System.Int32> value);
        partial void OncIdAreaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cIdTipoUsuario
        {
            get
            {
                return _cIdTipoUsuario;
            }
            set
            {
                OncIdTipoUsuarioChanging(value);
                ReportPropertyChanging("cIdTipoUsuario");
                _cIdTipoUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cIdTipoUsuario");
                OncIdTipoUsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _cIdTipoUsuario;
        partial void OncIdTipoUsuarioChanging(Nullable<global::System.Int32> value);
        partial void OncIdTipoUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cEstado
        {
            get
            {
                return _cEstado;
            }
            set
            {
                OncEstadoChanging(value);
                ReportPropertyChanging("cEstado");
                _cEstado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cEstado");
                OncEstadoChanged();
            }
        }
        private global::System.String _cEstado;
        partial void OncEstadoChanging(global::System.String value);
        partial void OncEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdTipPerBiblio
        {
            get
            {
                return _IdTipPerBiblio;
            }
            set
            {
                OnIdTipPerBiblioChanging(value);
                ReportPropertyChanging("IdTipPerBiblio");
                _IdTipPerBiblio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdTipPerBiblio");
                OnIdTipPerBiblioChanged();
            }
        }
        private global::System.String _IdTipPerBiblio;
        partial void OnIdTipPerBiblioChanging(global::System.String value);
        partial void OnIdTipPerBiblioChanged();

        #endregion

    
    }

    #endregion

    
}
