//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MesaPartes.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class OracleEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto OracleEntities usando la cadena de conexión encontrada en la sección 'OracleEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public OracleEntities() : base("name=OracleEntities", "OracleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto OracleEntities.
        /// </summary>
        public OracleEntities(string connectionString) : base(connectionString, "OracleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto OracleEntities.
        /// </summary>
        public OracleEntities(EntityConnection connection) : base(connection, "OracleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Z36> Z36
        {
            get
            {
                if ((_Z36 == null))
                {
                    _Z36 = base.CreateObjectSet<Z36>("Z36");
                }
                return _Z36;
            }
        }
        private ObjectSet<Z36> _Z36;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Z36. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToZ36(Z36 z36)
        {
            base.AddObject("Z36", z36);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MesaPartes", Name="Z36")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Z36 : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Z36.
        /// </summary>
        /// <param name="z36_REC_KEY">Valor inicial de la propiedad Z36_REC_KEY.</param>
        /// <param name="z36_ID">Valor inicial de la propiedad Z36_ID.</param>
        /// <param name="z36_NUMBER">Valor inicial de la propiedad Z36_NUMBER.</param>
        public static Z36 CreateZ36(global::System.String z36_REC_KEY, global::System.String z36_ID, global::System.String z36_NUMBER)
        {
            Z36 z36 = new Z36();
            z36.Z36_REC_KEY = z36_REC_KEY;
            z36.Z36_ID = z36_ID;
            z36.Z36_NUMBER = z36_NUMBER;
            return z36;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Z36_REC_KEY
        {
            get
            {
                return _Z36_REC_KEY;
            }
            set
            {
                if (_Z36_REC_KEY != value)
                {
                    OnZ36_REC_KEYChanging(value);
                    ReportPropertyChanging("Z36_REC_KEY");
                    _Z36_REC_KEY = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Z36_REC_KEY");
                    OnZ36_REC_KEYChanged();
                }
            }
        }
        private global::System.String _Z36_REC_KEY;
        partial void OnZ36_REC_KEYChanging(global::System.String value);
        partial void OnZ36_REC_KEYChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Z36_ID
        {
            get
            {
                return _Z36_ID;
            }
            set
            {
                if (_Z36_ID != value)
                {
                    OnZ36_IDChanging(value);
                    ReportPropertyChanging("Z36_ID");
                    _Z36_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Z36_ID");
                    OnZ36_IDChanged();
                }
            }
        }
        private global::System.String _Z36_ID;
        partial void OnZ36_IDChanging(global::System.String value);
        partial void OnZ36_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Z36_NUMBER
        {
            get
            {
                return _Z36_NUMBER;
            }
            set
            {
                if (_Z36_NUMBER != value)
                {
                    OnZ36_NUMBERChanging(value);
                    ReportPropertyChanging("Z36_NUMBER");
                    _Z36_NUMBER = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Z36_NUMBER");
                    OnZ36_NUMBERChanged();
                }
            }
        }
        private global::System.String _Z36_NUMBER;
        partial void OnZ36_NUMBERChanging(global::System.String value);
        partial void OnZ36_NUMBERChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_MATERIAL
        {
            get
            {
                return _Z36_MATERIAL;
            }
            set
            {
                OnZ36_MATERIALChanging(value);
                ReportPropertyChanging("Z36_MATERIAL");
                _Z36_MATERIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_MATERIAL");
                OnZ36_MATERIALChanged();
            }
        }
        private global::System.String _Z36_MATERIAL;
        partial void OnZ36_MATERIALChanging(global::System.String value);
        partial void OnZ36_MATERIALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_SUB_LIBRARY
        {
            get
            {
                return _Z36_SUB_LIBRARY;
            }
            set
            {
                OnZ36_SUB_LIBRARYChanging(value);
                ReportPropertyChanging("Z36_SUB_LIBRARY");
                _Z36_SUB_LIBRARY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_SUB_LIBRARY");
                OnZ36_SUB_LIBRARYChanged();
            }
        }
        private global::System.String _Z36_SUB_LIBRARY;
        partial void OnZ36_SUB_LIBRARYChanging(global::System.String value);
        partial void OnZ36_SUB_LIBRARYChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_STATUS
        {
            get
            {
                return _Z36_STATUS;
            }
            set
            {
                OnZ36_STATUSChanging(value);
                ReportPropertyChanging("Z36_STATUS");
                _Z36_STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_STATUS");
                OnZ36_STATUSChanged();
            }
        }
        private global::System.String _Z36_STATUS;
        partial void OnZ36_STATUSChanging(global::System.String value);
        partial void OnZ36_STATUSChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_LOAN_DATE
        {
            get
            {
                return _Z36_LOAN_DATE;
            }
            set
            {
                OnZ36_LOAN_DATEChanging(value);
                ReportPropertyChanging("Z36_LOAN_DATE");
                _Z36_LOAN_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_LOAN_DATE");
                OnZ36_LOAN_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_LOAN_DATE;
        partial void OnZ36_LOAN_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_LOAN_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Z36_LOAN_HOUR
        {
            get
            {
                return _Z36_LOAN_HOUR;
            }
            set
            {
                OnZ36_LOAN_HOURChanging(value);
                ReportPropertyChanging("Z36_LOAN_HOUR");
                _Z36_LOAN_HOUR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_LOAN_HOUR");
                OnZ36_LOAN_HOURChanged();
            }
        }
        private Nullable<global::System.Int16> _Z36_LOAN_HOUR;
        partial void OnZ36_LOAN_HOURChanging(Nullable<global::System.Int16> value);
        partial void OnZ36_LOAN_HOURChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_EFFECTIVE_DUE_DATE
        {
            get
            {
                return _Z36_EFFECTIVE_DUE_DATE;
            }
            set
            {
                OnZ36_EFFECTIVE_DUE_DATEChanging(value);
                ReportPropertyChanging("Z36_EFFECTIVE_DUE_DATE");
                _Z36_EFFECTIVE_DUE_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_EFFECTIVE_DUE_DATE");
                OnZ36_EFFECTIVE_DUE_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_EFFECTIVE_DUE_DATE;
        partial void OnZ36_EFFECTIVE_DUE_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_EFFECTIVE_DUE_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_DUE_DATE
        {
            get
            {
                return _Z36_DUE_DATE;
            }
            set
            {
                OnZ36_DUE_DATEChanging(value);
                ReportPropertyChanging("Z36_DUE_DATE");
                _Z36_DUE_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_DUE_DATE");
                OnZ36_DUE_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_DUE_DATE;
        partial void OnZ36_DUE_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_DUE_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Z36_DUE_HOUR
        {
            get
            {
                return _Z36_DUE_HOUR;
            }
            set
            {
                OnZ36_DUE_HOURChanging(value);
                ReportPropertyChanging("Z36_DUE_HOUR");
                _Z36_DUE_HOUR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_DUE_HOUR");
                OnZ36_DUE_HOURChanged();
            }
        }
        private Nullable<global::System.Int16> _Z36_DUE_HOUR;
        partial void OnZ36_DUE_HOURChanging(Nullable<global::System.Int16> value);
        partial void OnZ36_DUE_HOURChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_RETURNED_DATE
        {
            get
            {
                return _Z36_RETURNED_DATE;
            }
            set
            {
                OnZ36_RETURNED_DATEChanging(value);
                ReportPropertyChanging("Z36_RETURNED_DATE");
                _Z36_RETURNED_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_RETURNED_DATE");
                OnZ36_RETURNED_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_RETURNED_DATE;
        partial void OnZ36_RETURNED_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_RETURNED_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Z36_RETURNED_HOUR
        {
            get
            {
                return _Z36_RETURNED_HOUR;
            }
            set
            {
                OnZ36_RETURNED_HOURChanging(value);
                ReportPropertyChanging("Z36_RETURNED_HOUR");
                _Z36_RETURNED_HOUR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_RETURNED_HOUR");
                OnZ36_RETURNED_HOURChanged();
            }
        }
        private Nullable<global::System.Int16> _Z36_RETURNED_HOUR;
        partial void OnZ36_RETURNED_HOURChanging(Nullable<global::System.Int16> value);
        partial void OnZ36_RETURNED_HOURChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_ITEM_STATUS
        {
            get
            {
                return _Z36_ITEM_STATUS;
            }
            set
            {
                OnZ36_ITEM_STATUSChanging(value);
                ReportPropertyChanging("Z36_ITEM_STATUS");
                _Z36_ITEM_STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_ITEM_STATUS");
                OnZ36_ITEM_STATUSChanged();
            }
        }
        private global::System.String _Z36_ITEM_STATUS;
        partial void OnZ36_ITEM_STATUSChanging(global::System.String value);
        partial void OnZ36_ITEM_STATUSChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_BOR_STATUS
        {
            get
            {
                return _Z36_BOR_STATUS;
            }
            set
            {
                OnZ36_BOR_STATUSChanging(value);
                ReportPropertyChanging("Z36_BOR_STATUS");
                _Z36_BOR_STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_BOR_STATUS");
                OnZ36_BOR_STATUSChanged();
            }
        }
        private global::System.String _Z36_BOR_STATUS;
        partial void OnZ36_BOR_STATUSChanging(global::System.String value);
        partial void OnZ36_BOR_STATUSChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Z36_LETTER_NUMBER
        {
            get
            {
                return _Z36_LETTER_NUMBER;
            }
            set
            {
                OnZ36_LETTER_NUMBERChanging(value);
                ReportPropertyChanging("Z36_LETTER_NUMBER");
                _Z36_LETTER_NUMBER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_LETTER_NUMBER");
                OnZ36_LETTER_NUMBERChanged();
            }
        }
        private Nullable<global::System.Int16> _Z36_LETTER_NUMBER;
        partial void OnZ36_LETTER_NUMBERChanging(Nullable<global::System.Int16> value);
        partial void OnZ36_LETTER_NUMBERChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_LETTER_DATE
        {
            get
            {
                return _Z36_LETTER_DATE;
            }
            set
            {
                OnZ36_LETTER_DATEChanging(value);
                ReportPropertyChanging("Z36_LETTER_DATE");
                _Z36_LETTER_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_LETTER_DATE");
                OnZ36_LETTER_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_LETTER_DATE;
        partial void OnZ36_LETTER_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_LETTER_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Z36_NO_RENEWAL
        {
            get
            {
                return _Z36_NO_RENEWAL;
            }
            set
            {
                OnZ36_NO_RENEWALChanging(value);
                ReportPropertyChanging("Z36_NO_RENEWAL");
                _Z36_NO_RENEWAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_NO_RENEWAL");
                OnZ36_NO_RENEWALChanged();
            }
        }
        private Nullable<global::System.Int16> _Z36_NO_RENEWAL;
        partial void OnZ36_NO_RENEWALChanging(Nullable<global::System.Int16> value);
        partial void OnZ36_NO_RENEWALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_NOTE_1
        {
            get
            {
                return _Z36_NOTE_1;
            }
            set
            {
                OnZ36_NOTE_1Changing(value);
                ReportPropertyChanging("Z36_NOTE_1");
                _Z36_NOTE_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_NOTE_1");
                OnZ36_NOTE_1Changed();
            }
        }
        private global::System.String _Z36_NOTE_1;
        partial void OnZ36_NOTE_1Changing(global::System.String value);
        partial void OnZ36_NOTE_1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_NOTE_2
        {
            get
            {
                return _Z36_NOTE_2;
            }
            set
            {
                OnZ36_NOTE_2Changing(value);
                ReportPropertyChanging("Z36_NOTE_2");
                _Z36_NOTE_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_NOTE_2");
                OnZ36_NOTE_2Changed();
            }
        }
        private global::System.String _Z36_NOTE_2;
        partial void OnZ36_NOTE_2Changing(global::System.String value);
        partial void OnZ36_NOTE_2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_LOAN_CATALOGER_NAME
        {
            get
            {
                return _Z36_LOAN_CATALOGER_NAME;
            }
            set
            {
                OnZ36_LOAN_CATALOGER_NAMEChanging(value);
                ReportPropertyChanging("Z36_LOAN_CATALOGER_NAME");
                _Z36_LOAN_CATALOGER_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_LOAN_CATALOGER_NAME");
                OnZ36_LOAN_CATALOGER_NAMEChanged();
            }
        }
        private global::System.String _Z36_LOAN_CATALOGER_NAME;
        partial void OnZ36_LOAN_CATALOGER_NAMEChanging(global::System.String value);
        partial void OnZ36_LOAN_CATALOGER_NAMEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_LOAN_CATALOGER_IP
        {
            get
            {
                return _Z36_LOAN_CATALOGER_IP;
            }
            set
            {
                OnZ36_LOAN_CATALOGER_IPChanging(value);
                ReportPropertyChanging("Z36_LOAN_CATALOGER_IP");
                _Z36_LOAN_CATALOGER_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_LOAN_CATALOGER_IP");
                OnZ36_LOAN_CATALOGER_IPChanged();
            }
        }
        private global::System.String _Z36_LOAN_CATALOGER_IP;
        partial void OnZ36_LOAN_CATALOGER_IPChanging(global::System.String value);
        partial void OnZ36_LOAN_CATALOGER_IPChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RETURN_CATALOGER_NAME
        {
            get
            {
                return _Z36_RETURN_CATALOGER_NAME;
            }
            set
            {
                OnZ36_RETURN_CATALOGER_NAMEChanging(value);
                ReportPropertyChanging("Z36_RETURN_CATALOGER_NAME");
                _Z36_RETURN_CATALOGER_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RETURN_CATALOGER_NAME");
                OnZ36_RETURN_CATALOGER_NAMEChanged();
            }
        }
        private global::System.String _Z36_RETURN_CATALOGER_NAME;
        partial void OnZ36_RETURN_CATALOGER_NAMEChanging(global::System.String value);
        partial void OnZ36_RETURN_CATALOGER_NAMEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RETURN_CATALOGER_IP
        {
            get
            {
                return _Z36_RETURN_CATALOGER_IP;
            }
            set
            {
                OnZ36_RETURN_CATALOGER_IPChanging(value);
                ReportPropertyChanging("Z36_RETURN_CATALOGER_IP");
                _Z36_RETURN_CATALOGER_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RETURN_CATALOGER_IP");
                OnZ36_RETURN_CATALOGER_IPChanged();
            }
        }
        private global::System.String _Z36_RETURN_CATALOGER_IP;
        partial void OnZ36_RETURN_CATALOGER_IPChanging(global::System.String value);
        partial void OnZ36_RETURN_CATALOGER_IPChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RENEW_CATALOGER_NAME
        {
            get
            {
                return _Z36_RENEW_CATALOGER_NAME;
            }
            set
            {
                OnZ36_RENEW_CATALOGER_NAMEChanging(value);
                ReportPropertyChanging("Z36_RENEW_CATALOGER_NAME");
                _Z36_RENEW_CATALOGER_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RENEW_CATALOGER_NAME");
                OnZ36_RENEW_CATALOGER_NAMEChanged();
            }
        }
        private global::System.String _Z36_RENEW_CATALOGER_NAME;
        partial void OnZ36_RENEW_CATALOGER_NAMEChanging(global::System.String value);
        partial void OnZ36_RENEW_CATALOGER_NAMEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RENEW_CATALOGER_IP
        {
            get
            {
                return _Z36_RENEW_CATALOGER_IP;
            }
            set
            {
                OnZ36_RENEW_CATALOGER_IPChanging(value);
                ReportPropertyChanging("Z36_RENEW_CATALOGER_IP");
                _Z36_RENEW_CATALOGER_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RENEW_CATALOGER_IP");
                OnZ36_RENEW_CATALOGER_IPChanged();
            }
        }
        private global::System.String _Z36_RENEW_CATALOGER_IP;
        partial void OnZ36_RENEW_CATALOGER_IPChanging(global::System.String value);
        partial void OnZ36_RENEW_CATALOGER_IPChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RENEW_MODE
        {
            get
            {
                return _Z36_RENEW_MODE;
            }
            set
            {
                OnZ36_RENEW_MODEChanging(value);
                ReportPropertyChanging("Z36_RENEW_MODE");
                _Z36_RENEW_MODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RENEW_MODE");
                OnZ36_RENEW_MODEChanged();
            }
        }
        private global::System.String _Z36_RENEW_MODE;
        partial void OnZ36_RENEW_MODEChanging(global::System.String value);
        partial void OnZ36_RENEW_MODEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_BOR_TYPE
        {
            get
            {
                return _Z36_BOR_TYPE;
            }
            set
            {
                OnZ36_BOR_TYPEChanging(value);
                ReportPropertyChanging("Z36_BOR_TYPE");
                _Z36_BOR_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_BOR_TYPE");
                OnZ36_BOR_TYPEChanged();
            }
        }
        private global::System.String _Z36_BOR_TYPE;
        partial void OnZ36_BOR_TYPEChanging(global::System.String value);
        partial void OnZ36_BOR_TYPEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_NOTE_ALPHA
        {
            get
            {
                return _Z36_NOTE_ALPHA;
            }
            set
            {
                OnZ36_NOTE_ALPHAChanging(value);
                ReportPropertyChanging("Z36_NOTE_ALPHA");
                _Z36_NOTE_ALPHA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_NOTE_ALPHA");
                OnZ36_NOTE_ALPHAChanged();
            }
        }
        private global::System.String _Z36_NOTE_ALPHA;
        partial void OnZ36_NOTE_ALPHAChanging(global::System.String value);
        partial void OnZ36_NOTE_ALPHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_RECALL_DATE
        {
            get
            {
                return _Z36_RECALL_DATE;
            }
            set
            {
                OnZ36_RECALL_DATEChanging(value);
                ReportPropertyChanging("Z36_RECALL_DATE");
                _Z36_RECALL_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_RECALL_DATE");
                OnZ36_RECALL_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_RECALL_DATE;
        partial void OnZ36_RECALL_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_RECALL_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_RECALL_DUE_DATE
        {
            get
            {
                return _Z36_RECALL_DUE_DATE;
            }
            set
            {
                OnZ36_RECALL_DUE_DATEChanging(value);
                ReportPropertyChanging("Z36_RECALL_DUE_DATE");
                _Z36_RECALL_DUE_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_RECALL_DUE_DATE");
                OnZ36_RECALL_DUE_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_RECALL_DUE_DATE;
        partial void OnZ36_RECALL_DUE_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_RECALL_DUE_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_LAST_RENEW_DATE
        {
            get
            {
                return _Z36_LAST_RENEW_DATE;
            }
            set
            {
                OnZ36_LAST_RENEW_DATEChanging(value);
                ReportPropertyChanging("Z36_LAST_RENEW_DATE");
                _Z36_LAST_RENEW_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_LAST_RENEW_DATE");
                OnZ36_LAST_RENEW_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_LAST_RENEW_DATE;
        partial void OnZ36_LAST_RENEW_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_LAST_RENEW_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Z36_ORIGINAL_DUE_DATE
        {
            get
            {
                return _Z36_ORIGINAL_DUE_DATE;
            }
            set
            {
                OnZ36_ORIGINAL_DUE_DATEChanging(value);
                ReportPropertyChanging("Z36_ORIGINAL_DUE_DATE");
                _Z36_ORIGINAL_DUE_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Z36_ORIGINAL_DUE_DATE");
                OnZ36_ORIGINAL_DUE_DATEChanged();
            }
        }
        private Nullable<global::System.Int32> _Z36_ORIGINAL_DUE_DATE;
        partial void OnZ36_ORIGINAL_DUE_DATEChanging(Nullable<global::System.Int32> value);
        partial void OnZ36_ORIGINAL_DUE_DATEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_PROCESS_STATUS
        {
            get
            {
                return _Z36_PROCESS_STATUS;
            }
            set
            {
                OnZ36_PROCESS_STATUSChanging(value);
                ReportPropertyChanging("Z36_PROCESS_STATUS");
                _Z36_PROCESS_STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_PROCESS_STATUS");
                OnZ36_PROCESS_STATUSChanged();
            }
        }
        private global::System.String _Z36_PROCESS_STATUS;
        partial void OnZ36_PROCESS_STATUSChanging(global::System.String value);
        partial void OnZ36_PROCESS_STATUSChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_LOAN_TYPE
        {
            get
            {
                return _Z36_LOAN_TYPE;
            }
            set
            {
                OnZ36_LOAN_TYPEChanging(value);
                ReportPropertyChanging("Z36_LOAN_TYPE");
                _Z36_LOAN_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_LOAN_TYPE");
                OnZ36_LOAN_TYPEChanged();
            }
        }
        private global::System.String _Z36_LOAN_TYPE;
        partial void OnZ36_LOAN_TYPEChanging(global::System.String value);
        partial void OnZ36_LOAN_TYPEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_PROXY_ID
        {
            get
            {
                return _Z36_PROXY_ID;
            }
            set
            {
                OnZ36_PROXY_IDChanging(value);
                ReportPropertyChanging("Z36_PROXY_ID");
                _Z36_PROXY_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_PROXY_ID");
                OnZ36_PROXY_IDChanged();
            }
        }
        private global::System.String _Z36_PROXY_ID;
        partial void OnZ36_PROXY_IDChanging(global::System.String value);
        partial void OnZ36_PROXY_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RECALL_TYPE
        {
            get
            {
                return _Z36_RECALL_TYPE;
            }
            set
            {
                OnZ36_RECALL_TYPEChanging(value);
                ReportPropertyChanging("Z36_RECALL_TYPE");
                _Z36_RECALL_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RECALL_TYPE");
                OnZ36_RECALL_TYPEChanged();
            }
        }
        private global::System.String _Z36_RECALL_TYPE;
        partial void OnZ36_RECALL_TYPEChanging(global::System.String value);
        partial void OnZ36_RECALL_TYPEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RETURN_LOCATION
        {
            get
            {
                return _Z36_RETURN_LOCATION;
            }
            set
            {
                OnZ36_RETURN_LOCATIONChanging(value);
                ReportPropertyChanging("Z36_RETURN_LOCATION");
                _Z36_RETURN_LOCATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RETURN_LOCATION");
                OnZ36_RETURN_LOCATIONChanged();
            }
        }
        private global::System.String _Z36_RETURN_LOCATION;
        partial void OnZ36_RETURN_LOCATIONChanging(global::System.String value);
        partial void OnZ36_RETURN_LOCATIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RETURN_SUB_LOCATION
        {
            get
            {
                return _Z36_RETURN_SUB_LOCATION;
            }
            set
            {
                OnZ36_RETURN_SUB_LOCATIONChanging(value);
                ReportPropertyChanging("Z36_RETURN_SUB_LOCATION");
                _Z36_RETURN_SUB_LOCATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RETURN_SUB_LOCATION");
                OnZ36_RETURN_SUB_LOCATIONChanged();
            }
        }
        private global::System.String _Z36_RETURN_SUB_LOCATION;
        partial void OnZ36_RETURN_SUB_LOCATIONChanging(global::System.String value);
        partial void OnZ36_RETURN_SUB_LOCATIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_SOURCE
        {
            get
            {
                return _Z36_SOURCE;
            }
            set
            {
                OnZ36_SOURCEChanging(value);
                ReportPropertyChanging("Z36_SOURCE");
                _Z36_SOURCE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_SOURCE");
                OnZ36_SOURCEChanged();
            }
        }
        private global::System.String _Z36_SOURCE;
        partial void OnZ36_SOURCEChanging(global::System.String value);
        partial void OnZ36_SOURCEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_DELIVERY_TIME
        {
            get
            {
                return _Z36_DELIVERY_TIME;
            }
            set
            {
                OnZ36_DELIVERY_TIMEChanging(value);
                ReportPropertyChanging("Z36_DELIVERY_TIME");
                _Z36_DELIVERY_TIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_DELIVERY_TIME");
                OnZ36_DELIVERY_TIMEChanged();
            }
        }
        private global::System.String _Z36_DELIVERY_TIME;
        partial void OnZ36_DELIVERY_TIMEChanging(global::System.String value);
        partial void OnZ36_DELIVERY_TIMEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_TAIL_TIME
        {
            get
            {
                return _Z36_TAIL_TIME;
            }
            set
            {
                OnZ36_TAIL_TIMEChanging(value);
                ReportPropertyChanging("Z36_TAIL_TIME");
                _Z36_TAIL_TIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_TAIL_TIME");
                OnZ36_TAIL_TIMEChanged();
            }
        }
        private global::System.String _Z36_TAIL_TIME;
        partial void OnZ36_TAIL_TIMEChanging(global::System.String value);
        partial void OnZ36_TAIL_TIMEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_UPD_TIME_STAMP
        {
            get
            {
                return _Z36_UPD_TIME_STAMP;
            }
            set
            {
                OnZ36_UPD_TIME_STAMPChanging(value);
                ReportPropertyChanging("Z36_UPD_TIME_STAMP");
                _Z36_UPD_TIME_STAMP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_UPD_TIME_STAMP");
                OnZ36_UPD_TIME_STAMPChanged();
            }
        }
        private global::System.String _Z36_UPD_TIME_STAMP;
        partial void OnZ36_UPD_TIME_STAMPChanging(global::System.String value);
        partial void OnZ36_UPD_TIME_STAMPChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_LOAN_CATALOGER_IP_V6
        {
            get
            {
                return _Z36_LOAN_CATALOGER_IP_V6;
            }
            set
            {
                OnZ36_LOAN_CATALOGER_IP_V6Changing(value);
                ReportPropertyChanging("Z36_LOAN_CATALOGER_IP_V6");
                _Z36_LOAN_CATALOGER_IP_V6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_LOAN_CATALOGER_IP_V6");
                OnZ36_LOAN_CATALOGER_IP_V6Changed();
            }
        }
        private global::System.String _Z36_LOAN_CATALOGER_IP_V6;
        partial void OnZ36_LOAN_CATALOGER_IP_V6Changing(global::System.String value);
        partial void OnZ36_LOAN_CATALOGER_IP_V6Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RETURN_CATALOGER_IP_V6
        {
            get
            {
                return _Z36_RETURN_CATALOGER_IP_V6;
            }
            set
            {
                OnZ36_RETURN_CATALOGER_IP_V6Changing(value);
                ReportPropertyChanging("Z36_RETURN_CATALOGER_IP_V6");
                _Z36_RETURN_CATALOGER_IP_V6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RETURN_CATALOGER_IP_V6");
                OnZ36_RETURN_CATALOGER_IP_V6Changed();
            }
        }
        private global::System.String _Z36_RETURN_CATALOGER_IP_V6;
        partial void OnZ36_RETURN_CATALOGER_IP_V6Changing(global::System.String value);
        partial void OnZ36_RETURN_CATALOGER_IP_V6Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z36_RENEW_CATALOGER_IP_V6
        {
            get
            {
                return _Z36_RENEW_CATALOGER_IP_V6;
            }
            set
            {
                OnZ36_RENEW_CATALOGER_IP_V6Changing(value);
                ReportPropertyChanging("Z36_RENEW_CATALOGER_IP_V6");
                _Z36_RENEW_CATALOGER_IP_V6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z36_RENEW_CATALOGER_IP_V6");
                OnZ36_RENEW_CATALOGER_IP_V6Changed();
            }
        }
        private global::System.String _Z36_RENEW_CATALOGER_IP_V6;
        partial void OnZ36_RENEW_CATALOGER_IP_V6Changing(global::System.String value);
        partial void OnZ36_RENEW_CATALOGER_IP_V6Changed();

        #endregion

    
    }

    #endregion

    
}
